name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

        
      - name: Install Python Dependencies
        run: |
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


      - name: Run Python Script to Modify Android Project
        run: python test.py  # Runs your Python automation script

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permissions for Gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: updated-app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
